[package]
name = "rindex"
version = "0.1.0"
edition = "2021"

[dependencies]
allocator-api2 = "0.2.16"
arc-swap = "1.6.0"
bumpalo = { version = "3.14.0", features = ["allocator-api2"] }
downcast-rs = "1.2.0"
